### ISSUE TITLE
Problems with simultaneous master/slave

### ISSUE THREAD

**Issue by haimiko** [watterott/ATmega328PB-Testing#50]
Hangs when I try to run as an I2C slave on SDA0/SCL0 and Master on SDA1/SCL1.  Everything appears to initialize properly.  When I run Wire.begin(8) my remote master can see this device and i can see other slave devices on SDA1. However, as soon as I query a slave device on SDA1, the SDA0 bus goes LOW and because of that longer responds as a slave on SDA0.

**Comment by awatterott** [comment]
The Wire1 lib deactivated the pullups from SDA0 and SCL0. I have fixed it now and I will release a new boards package soon.
https://github.com/watterott/ATmega328PB-Testing/commit/3ed2913c79806d61b47964d342f125fa49a116ca

**Comment by haimiko** [comment]
> 
> 
> The Wire1 lib deactivated the pullups from SDA0 and SCL0. I have fixed it now and I will release a new boards package soon.
> Commit: [3ed2913](https://github.com/watterott/ATmega328PB-Testing/commit/3ed2913c79806d61b47964d342f125fa49a116ca)

Nice catch but still didn't resolve the issue.  Must be some other reference somewhere too.

**Comment by awatterott** [comment]
I have looked over the code again, but I dont see any problems.
Can you make a minimal example to re-produce the problem.
